### ISSUE TITLE
Feature request: Control over transaction inclusion in blocks

### ISSUE THREAD

**Issue by PeterBorah** [ConsenSys-archive/ganache-cli-archive#108]
It would be useful to have fine-grained control over blocks and the transactions they include. This would allow you to test situations where multiple transactions are in the same block, the precise block number matters, or large numbers of blocks pass between transactions.
## Expected Behavior

Various implementations are possible, but for example:

You send `testrpc` the request to enter Manual Block mode. From that point, until you request it return to normal mode, it does not automatically advance blocks every time it receives a transaction. Instead, it queues the transactions it receives until it receives the command to advance a block, at which point it does so and includes any queued transactions.
## Current Behavior

`testrpc` currently advances 1 block per transaction.
## Context

In multi-user scenarios, blocks are often used as proxies for elapsed time. It is therefore necessary to be able to test situations that occur only at specific block heights.

Additionally, there may be situations where you want to specifically test multiple transactions in the same block. For instance, if you have an oracle which only wants to reward a user for updating it at most once per block.

**Comment by tcoulter** [comment]
- [ ] As a feature of this block processing strategy, whenever a block is requested to be mined, you can optionally pass the timestamp of the block to accurately test time code that's based on the passage of time. One condition of this feature is that you shouldn't be able to mine a block in the past. See comments in #52 for more discussion.

**Comment by tcoulter** [comment]
@PeterBorah Everything you requested above has been added to the `develop` branch, primarily written by @area. The flow goes like this:
1. Send `miner_stop` request to the TestRPC to stop default mining behavior (i.e., instamine).
2. Queue transactions; they won't be mined when queued.
3. Send `evm_mine` request when you'd like to advance a block. Note that queued transactions are ordered by nonce and gas limit, so if you have a set of transactions whose gas limits total more than the default block gas limit, only a portion of those transactions will be mined (filing up the block without going over).
4. To start normal instamining again, send `miner_start` request to the TestRPC. The `miner_start`/`miner_stop` mimic the requests from `geth`.

I still need to test that `evm_mine` works correctly with the new flow, especially when handling error cases. I'd like `evm_mine` to return errors like OOG, but I have to see what I can do when multiple transactions are queued. Perhaps if you're queueing transactions, you forfeit the right to errors in the response since you're instamining. Not sure.

I'll attempt to write a test for this now / tomorrow morning.

**Comment by tcoulter** [comment]
@area @PeterBorah I need some feedback here. What would you expect to happen if a transaction failed during `evm_mine`, say, with the error `invalid JUMP`, and it were mined in a block with another valid transaction? Now consider both transactions failed. What should happen as a result of the `evm_mine` request? Couple scenarios:
1. Should the `evm_mine` request return an error with the first error encountered, ignoring other errors?
2. Should the `evm_mine` request return an error of a type that tries to merge the results of all transactions that failed?
3. Should the `evm_mine` request **not** return an error, and instead return the underlying vm results for each transaction, which include the error messages of each transaction (requires digging by the user and understanding of the vm results)
4. Should the `evm_mine` request return an error of a type like the above **and** return the vm results?
5. Should the `evm_mine` request **not** error and **not** return the vm results, acting simply like a real blockchain? (i.e., you're not privy to the types of errors with `geth`).

Which do you think its better? Have any other suggestions?

**Comment by area** [comment]
Have you changed your opinion since the discussion at https://github.com/ethereumjs/testrpc/issues/39 , and would consider option 5, or are you simply trying to enumerate all possible options here?

I think behaviour should be consistent between insta-mining and this sort of mining, so my most preferred option is probably 1, followed by 2, 4, 5, 3.

**Comment by tcoulter** [comment]
Enumerating all possible options for you guys to consider. My general _desire_ is to expose the errors; but it's awkward when there are multiple errors per block. 

I'm actually leaning toward (2), but only if we create an Error object that parses the VM result per block and is always returned if an error occurs, no matter if it's a transaction with `instamine`, a mining request via `evm_mine`, or restarting mining via `miner_start`.

The one counter point is that mining on interval is sufficiently asynchronous. With `--blocktime`, we couldn't return the error if we wanted to because the error would exist outside of the user's control flow. I'm okay with this, as I'd call it an "advanced" usage of the TestRPC. One potentially sticky area however is `miner_start`; this has the potential to mine multiple blocks of which multiple transactions in each block could error. We'd have to have an error handler that merged all of these.

In any case, the above is mostly thinking out loud to get it "on paper". I think I'm set on (2) even though it's going to take some work to write tests for all these cases. That said, in the end it should be worth it. 

Thanks for the feedback, as always.

**Comment by tcoulter** [comment]
Putting more on paper, here's the cases which I'll write tests for and ensure proper error handling:
- [x] Processing a single erroneous transaction via `instamine`. 
- [x] Processing multiple erroneous transactions via `miner_stop`/`miner_start` that exist in the same block
- [x] Processing multiple erroneous transactions via `miner_stop`/`miner_start` that exist in multiple blocks

To do this, I'll:
- [x] Create a custom Error object and/or VM results interpreter that processes VM results and handles multiple errors
- [x] Give the custom Error object the ability to combine its errors with more VM results, adding multiple transactions errors into the same error object (for `miner_start` with multiple blocks)

What I'm thinking this will turn into from a user's standpoint is an error message that looks like this:

> Error: Multiple transaction errors: invalid JUMP; OOG; 

Or even better, perhaps:

> Error: Multiple transaction errors:
> 
> 0xabcd...1234: Invalid JUMP
> 0x1234...abcd: OOG

When using the TestRPC as a library instead of a server, you'll receive this error object itself and can drill down into its data, something like:

``` javascript
console.log(err.results)
// {
//   "0xabcd...1234": "Invalid JUMP"
//   "0x1234...abcd": "OOG"
// }
```

One last note: If `--blocktime` is used, I'll print the error in the TestRPC logs since it can't be handled (this will likely be a different ticket).

**Comment by tcoulter** [comment]
Dag nabit. One great edge case:
- [x] If one transaction errors and one succeeds, the logs for the successful transaction still need to be processed.

**Comment by tcoulter** [comment]
Alright, better error handling scheme pushed to `develop`, with tests. I'm calling this ticket done!

**Comment by okwme** [comment]
i'm trying this out and not getting the results as i expected. I'd like to make sure a series of transactions are included in the same block. However with automining each transaction causes a new block to be mined. If I understand the use of `miner_start` and `miner_stop` correctly then i should be able to do:
```javascript
async function batchTransactions() {
    let currentBlock = await blockNumber()
    console.log({ currentBlock })

    await stopMining()

    const promise1 = contract.makeTX()
    const promise2 = contract.makeTX()
    const promise3 = contract.makeTX()

    await startMining()
    
    const results = await Promise.all([promise1, promise2, promise3])

    currentBlock = await blockNumber()
    console.log({ currentBlock })
}

function blockNumber() {
  return new Promise((resolve, reject) => {
    web3.eth.getBlockNumber(async (err, res) => {
      if (err || !res) return reject(err)
      resolve(res)
    })
  })
}

function stopMining() {
  return new Promise((resolve, reject) => {
    web3.currentProvider.sendAsync(
      {
        jsonrpc: '2.0',
        method: 'miner_stop',
        id: 12346,
      },
      (err, result) => {
        if (err) reject(err)
        resolve(result)
      }
    )
  })
}

function startMining() {
  return new Promise((resolve, reject) => {
    web3.currentProvider.sendAsync(
      {
        jsonrpc: '2.0',
        method: 'miner_start',
        id: 12347,
      },
      (err, result) => {
        if (err) reject(err)
        resolve(result)
      }
    )
  })
}
```
However I get that each transaction was again included in it's own block and the current block number has progressed 3 blocks instead of 1.

What am I doing wrong?
