### ISSUE TITLE
Feature request: Mine a chosen amount blocks per transaction.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys-archive/ganache-cli-archive#12]
Some dapps watch for a certain amount of blocks before accepting a transaction as finalised.

Would be useful to have a feature/setting to allow testrpc to mine a certain amount of blocks for each tx. And set it upon running it. Something like: 

```
testrpc --blockspertx 10
```

**Comment by tcoulter** [comment]
Added to v0.2.0 milestone (next release)

**Comment by tcoulter** [comment]
Just added a Command Line Arguments section to the README. As this feature is updated, make sure to add the `--blockspertx` (and `-b`? up to you) to that section.

**Comment by kumavis** [comment]
i like the term "sleepy mining" but thats just me

**Comment by simondlr** [comment]
I see in geth you can do sleepblocks. So that terminology could help? blockpertx seems descriptive so far.

**Comment by tcoulter** [comment]
Following up on this ticket. There are two features that have been added since this ticket was written that will allow for the behavior you're looking for. 
1. `--blocktime`: You can tell the TestRPC to mine blocks on a configurable interval, thus supporting dapps that require a transaction be finalized.
2. `evm_mine` request: Will mine a block per request. You can throw this on a loop (or `async.times`, etc.) if you'd like to mine more than one block.

See [README](https://github.com/ethereumjs/testrpc) for more details.
