### ISSUE TITLE
eth_getStorageAt returns '0x00' everytimes

### ISSUE THREAD

**Issue by louptheron** [ConsenSys-archive/ganache-cli-archive#133]
`web3.eth.getStorageAt()` returns '0x00' when using `testrpc`, but work fine with `geth`.
## Expected Behavior

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetstorageat
## Steps to Reproduce (for bugs)

I deploy a contract, set a variable in it, and then check it using : 

```
web3.eth.getStorageAt(address, 0)
```
## Your Environment

EthereumJS TestRPC v2.0.7

**Comment by tcoulter** [comment]
We have tests that sufficiently test `eth_getStorageAt`, so it's unlikely it's simply not working. You need to make sure you have your storage position correct. Are you sure that your variable is stored at position 0? Not all data is sequentially stored, so some will be stored at a specific hash position rather than incrementally.

I'm going to close this for housekeeping. But if you can provide code examples of why this isn't working, and that same code works on geth, we can reopen and investigate.

**Comment by aakilfernandes** [comment]
https://github.com/ethereumjs/testrpc/blob/2ad83898d8d54e127d0df086360be64a56e7e96a/test/requests.js#L516

This test fails if `contract.position_of_value` is replaced with `0` or `0x0`. Digging into it now

**Comment by aakilfernandes** [comment]
Fixed on https://github.com/ethereumjs/testrpc/tree/getStorageAt-0, needs merge
