### ISSUE TITLE
error while installing testrpc

### ISSUE THREAD

**Issue by coderwithattitude** [ConsenSys-archive/ganache-cli-archive#161]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by amrikmahal** [comment]
Expected Behavior: Able to install testrpc.

Current Behavior: Getting error while installing

Possible Solution: Not sure

Steps to Reproduce (for bugs)
I am following the steps from here https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows
1.When i run this commend [npm install -g ethereumjs-testrpc] i  am getting errors related to 
[error summary.txt](https://github.com/ethereumjs/testrpc/files/478391/error.summary.txt)

[npm error log.txt](https://github.com/ethereumjs/testrpc/files/478388/npm.error.log.txt)

2.
3.
4.

Context

Your Environment

Version used:
Environment name and version Windows 10
Server type and version:
Operating System and version: Windows 10 enterprise
Link to your project:

**Comment by chevdor** [comment]
Helloe @CoderWithAttitude,
Do you still have the problem? Did you test with the new version 3.0.0?
I see that you opened 2 times the same issue (see #160)
It would be great if you could bring the details over into this issue and close #160 to avoid the duplicates. Since @amrikmahal commented here, it is probably better to keep this issue.
You can Edit your initial issue, there is an edit button (little pen on the upper right corner).

**Comment by jmdfm** [comment]
@amrikmahal Please read the error output before creating issues. It clearly shows the following: 

`Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?`

Once you have addressed all system issues on your machine, if this error is still occurring please feel free to reopen.
