### ISSUE TITLE
CORS - Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#17]
XMLHttpRequest cannot load http://localhost:8545/. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by kumavis** [comment]
I think you just havent published the latest version yet

**Comment by sebs** [comment]
oh yeah, we need this.

**Comment by tcoulter** [comment]
@sebs CORS headers have been added for a long time. Are you having trouble with them?

**Comment by sebs** [comment]
yeah, I want to add some extra headers, that need to be configured. 
Otherwise all calls with extra headers to OPTIONS will fail. 

Stuff like this. 
https://www.w3.org/TR/cors/#access-control-allow-headers-response-header

If you start to use extra headers for maybe a little added extra security, testrpc is a bit to "secure" atm. Imho those options are not avail. via command line parameter.

**Comment by BinayakBanerjee** [comment]
still facing cors issue while connecting testrpc, any solutions folks ? getting no response to OPTIONS request.

**Comment by davidmurdoch** [comment]
@BinayakBanerjee Could you open a new issue for this with a little more information about your particular configuration, versions, and os, and browser/client?

**Comment by BinayakBanerjee** [comment]
@davidmurdoch Nevermind, reinstalled testrpc. Seems to be working fine now.
