### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Alonski** [ConsenSys-archive/ganache-cli-archive#175]
![testrpc](https://cloud.githubusercontent.com/assets/452199/19189856/d6f027fe-8ca2-11e6-848b-7aa0a9683d61.PNG)
[npm-debug.txt](https://github.com/ethereumjs/testrpc/files/509066/npm-debug.txt)

## Expected Behavior

Running "npm install -g ethereumjs-testrpc" in Windows CMD, Powershell, GitBash installs testrpc.
## Current Behavior

Get error while installing and install doesn't work.
## Possible Solution

Don't know....
## Steps to Reproduce (for bugs)

1. Run npm install -g ethereumjs-testrpc
   2.
   3.
   4.
## Context

Can't install
## Your Environment

- Version used: Newest?
- Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Windows 10 64
- Server type and version: Windows 10 64
- Operating System and version: Windows 10 64
- NodeJs Version: Node 6.7.0

**Comment by tcoulter** [comment]
Hi @Alonski. When writing an issue that results in an error, please include the error. We can't help you otherwise.

That said, have you followed our [Windows install instructions](https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows)? I'm going to close this ticket. Please reopen after you've followed these instructions and are still receiving an error. Please post the full error message in the issue or else there's nothing we can do to help.

Thanks!

**Comment by Alonski** [comment]
Sorry I forgot to add my Log!
Anyways yes I did try the Windows install instructions. Still couldn't get it to work.

Can I Reopen this issue myself?

**Comment by tcoulter** [comment]
Not against reopening, but I'm going to need the error message you're receiving in order to help.

**Comment by tcoulter** [comment]
Hmm, I didn't realize you added the log at the top of the issue. Can you give the error message you're receiving as well? That log is very verbose - hard to track down whee to start.

**Comment by Alonski** [comment]
I included npm-debug at the top. Anything else?

**Comment by Alonski** [comment]
@tcoulter 
Added a screenshot of my errors... Hope this helps.

**Comment by tcoulter** [comment]
Helps a lot. From [this link](https://github.com/nodejs/node-gyp/issues/972) it appears you just need to run `npm -g install npm@next`, or follow what other people have tried there.
