### ISSUE TITLE
slow contract setup

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ConsenSys-archive/ganache-cli-archive#21]
have a contract deployment setup which takes about 20s with `ethereumjs-testrpc` but <1s with `eth-testrpc`
it basically chains 6 contracts by doing

```
Foo.new(...).then(function(newFoo) { return Bar.new(newFoo.address).then(function(newBar) { ...
```

I'm guessing there's one block between each deployment, but not sure why it's so much slower with `ethereumjs-testrpc`
wondering if I'm using promises incorrectly and there's a way to deploy all contracts sequentially in one block

**Comment by tcoulter** [comment]
Hi @Gustav-Simonsson. The TestRPC has been significantly updated since you wrote this issue. I'm going to close it as I haven't seen this slowdown myself. However, if you're still running into the issue, definitely submit a new ticket with the code you're deploying that's slowing it down. 

To answer your question specifically, it does appear you are using promises correctly. Cheers!
