### ISSUE TITLE
Forking Parity results in state_pruned error

### ISSUE THREAD

**Issue by Schaeff** [ConsenSys-archive/ganache-cli-archive#210]
## Expected Behavior
When forking another network using `--fork`, it should be transparent if we're connected to the original chain or the fork

## Current Behavior
When forking Parity 1.4.4, Parity complains about the state being pruned when doing `eth_call`:
`This request is not supported because your node is running with state pruning. Run with --pruning=archive.`
The same request when connecting directly to the Parity node succeeds.

## Steps to Reproduce (for bugs)
1. Spin up Parity node
2. Send `eth_call` RPC call to Parity node
3. Fork Parity node with `testrpc --fork $NODE_URL`
4. Send `eth_call` RPC call to testrpc

## Context
I'm setting up a dev environment for CI and want it to replicate my production environment.

## Your Environment
* Version used: 3.0.2
* Environment name and version: Node.js 6.3.0, Parity 1.4.4

**Comment by benjamincburns** [comment]
Hi @Schaeff,

Thanks for submitting the issue! I think this is probably a problem with Pairity. What happens when you run pairity with the `--pruning=archive` flag, as suggested in the error message?

Essentially, I think Pairity is dropping some of the data in the blockchain which it thinks is no longer relevant. Passing this flag should cause it to no longer do this.

Closing as I assume this will fix things for you. Please reopen if you feel this is still an issue.
