### ISSUE TITLE
TestRPC returns error for throws but Geth returns fine

### ISSUE THREAD

**Issue by slothbag** [ConsenSys-archive/ganache-cli-archive#214]
Firstly thanks for TestRPC, it is a really great tool.

I am trying to write some solidity test scripts and run the same test script against TestRPC and Geth.  However if the tx causes a `throw` then TestRPC returns the error to the RPC request which causes the test to fail.  However the same tx to Geth submits fine, returning a valid response to the RPC but then fails in the EVM and consumes all the gas.

Is it possible to have a flag in TestRPC so that transactions that fail still behave like Geth and return a valid submission result but show the gasUsed = gasProvided when doing eth_getTransactionReceipt?

**Comment by benjamincburns** [comment]
Hi, @slothbag.

I think using interval mining instead of instamining will do what you want. You can do this by simply specifying a block time with the `-b` or `--blocktime` flag.

With instamining we run your transaction as part of the request, and report back any VM errors which occur. Unfortunately this means that we sacrifice a small amount of consistency with respect to how we return errors, but from that you gain a much higher degree of insight as to what went wrong with your contract than you would have gotten otherwise. Fortunately, interval mining puts things back the way you'd expect.

Even though this is expected behavior, I appreciate you bringing it to our attention!

Closing this for now under the assumption that this answers the question. If you need more info, or if you feel like I missed something, please comment/reopen.
