### ISSUE TITLE
Windows install guidlines wiki improvement.

### ISSUE THREAD

**Issue by 4c656554** [ConsenSys-archive/ganache-cli-archive#237]
Windows install guidlines wiki improvement.

This wiki https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows asks to post an issue for suggested edits:

I'd suggest replacing step five with:

5. Install npm for Windows: https://nodejs.org/en/

**Comment by Airum** [comment]
Yes please!

**Comment by benjamincburns** [comment]
@4c656554 thanks for filing an issue, and sorry that it sat for so long!

We've since fixed things up quite a bit so that installing in windows is _much_ more straightforward. I've edited the wiki to reflect this, and I've included the link you've suggested.

https://github.com/ethereumjs/testrpc/wiki/Installing-TestRPC-on-Windows
