### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by HCharlanes** [ConsenSys-archive/ganache-cli-archive#247]
I used testrpc and go this error after hitting it pretty badly.

```
<--- Last few GCs --->

11423918 ms: Mark-sweep 1330.1 (1434.6) -> 1322.3 (1434.6) MB, 2523.2 / 0.2 ms [allocation failure] [GC in old space requested].
11426273 ms: Mark-sweep 1322.3 (1434.6) -> 1322.3 (1434.6) MB, 2354.8 / 0.0 ms [allocation failure] [GC in old space requested].
11428632 ms: Mark-sweep 1322.3 (1434.6) -> 1323.8 (1405.6) MB, 2357.9 / 0.0 ms [last resort gc].
11431561 ms: Mark-sweep 1323.8 (1405.6) -> 1325.4 (1405.6) MB, 2928.7 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f8b46bcfb51 <JS Object>
    1: _writeGeneric [net.js:697] [pc=0x36f59faecfac] (this=0x706b75c32e9 <a Socket with map 0x1627d3905bc9>,writev=0x3f8b46b043c1 <true>,data=0x32354ee577e9 <JS Array[2]>,encoding=0x3f8b46b04411 <String[0]: >,cb=0x3e67babe4511 <JS Function WritableState.onwrite (SharedFunctionInfo 0x39f259c841b9)>)
    2: doWrite(aka doWrite) [_stream_writable.js:~326] [pc=0x36f59fa136f3] (this=0x3f8b46b04381 ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Abort trap: 6
```

Using EthereumJS TestRPC v3.0.3: 
 For 200 min. 
1 bot sending 1 tx every 5 sec [To a factory that creates a contract and register it into a Registry i.e 1 external + 2 internal tx, fires 1 Event].
1 bot sending 1 tx every 5 sec [To the factory that sends 2  internal txs, fires 2 Events]
1 bot getting Events every 5 sec (through web3.eth.contract.allEvents.get)

Summary:
200 min  
Around 2500 external tx
Around 5000 internal tx
Around 5000 events pulled from testrpc.

**Comment by tcoulter** [comment]
This is now fixed on the `persistence` branch: https://github.com/ethereumjs/testrpc/pull/275

TL;DR: There's no more memory issues because the data is no longer stored in memory; it's now stored on disk. In my tests with tens of thousands of requests, this branch never got above 250Mb of memory usage on my machine. Compare that to the previous version of the TestRPC (3.0.3), which I was able to make hit 800Mb of memory quite easily.

I'm going to close this ticket for now, although it won't be _completely_ fixed until a new released is pushed. Keep a look out for the next version (4.0.0) which should be out soon.
