### ISSUE TITLE
Return "invalid params" error when too many arguments are given

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#255]
https://github.com/ethereum/wiki/blob/master/JSON-RPC-Error-Codes-Improvement-Proposal.md

This is implemented in geth at least

**Comment by benjamincburns** [comment]
Thanks for reporting this @aakilfernandes - I'm sorry it's gone unnoticed for so long!

I ran into this today, myself. I'll make sure it's fixed in time for the full-blown 7.0 release.

Note to self or anyone who wants to take this on as a PR: to fix, add a check for `request.params.length <= method.length - 1` in geth_api_double's handleAsync, plus relevant tests.

**Comment by benjamincburns** [comment]
Thanks for reporting this, @aakilfernandes and @rmeissner! This issue is now fixed, and will go out in the next release!
