### ISSUE TITLE
Running testrpc with https

### ISSUE THREAD

**Issue by Moejoe90** [ConsenSys-archive/ganache-cli-archive#304]
Just a suggestion, 
Is there a way for the testRPC team to put in there plan the option of setting up an https connection instead of the regular http?

**Comment by IstoraMandiri** [comment]
Use a reverse proxy server such as nginx 

See https://github.com/kovan-testnet/rpc-node-setup (instead of parity, install testrpc)

**Comment by Moejoe90** [comment]
Cool thanks for that

**Comment by recmo** [comment]
In my setup I use `webpack-dev-server` with the `--https` flag (I need this for unrelated reasons). Https does not allow requests to http, so I needed a way to access testrpc in my setup.

If you add the following to your `webpack.config.js` then you can access the web3 api at `/web3/`:
```
devServer: {
    …
    proxy: {
      '/web3/*': {
        target: 'http://localhost:8545'
      }
}
```

**Comment by Moejoe90** [comment]
I'm using the same trick, but i was hopping that there would be a real solution trough testRPC. I assume its not a priority nor in the plan for testRPC

**Comment by benjamincburns** [comment]
Unfortunately https support is not likely something we want to maintain, as it comes with certificate issues, etc. Were the ganache suite meant to be used outside of a dev context it'd make more sense. In the mean time if you _really_ need this, the correct way to add it to your environment is to use an HTTP reverse proxy with support for HTTPS. I wasn't aware that `webpack-dev-server` supported proxying _or_ https, as @Recmo shows, but since it does, it's probably easier to use than my would-be recommendation to use nginx.

Closing this issue since we won't add this functionality, however I would love to accept a PR which adds @Recmo's workaround to the README.
