### ISSUE TITLE
DELEGATECALL should receive only 63/64 of the remaining gas (and msg.gas should reflect that)

### ISSUE THREAD

**Issue by carver** [ConsenSys-archive/ganache-cli-archive#367]
A `DELEGATECALL` instruction should receive 63/64 of the remaining gas, but appears to be receiving the full remaining gas (according to a `msg.gas` call in solidity).

The gas used is defined in the [yellow paper](http://gavwood.com/paper.pdf) at Cgascap

![Cgascap definition](https://i.stack.imgur.com/ixo0b.png)

Function L is defined in equation 224 on page 22: `L(n) ≡ n − floor(n/64)`

The Stackoverflow answer that inspired this report is [here](https://ethereum.stackexchange.com/a/23592/1461).

Tested this contract:
```
pragma solidity ^0.4.13;

contract TestDepth {
    uint256 public x;

    function depth(uint256 y) {
        if (y > 0) {
            this.delegatecall(bytes4(sha3('depth(uint256)')), --y);
        }
        else {
             // Save the remaining gas in storage so that we can access it later
             x = msg.gas;
        }
    }
}
```

## Expected Behavior

The value of x when called with y:
y=0, x=2.98M
y=1, x~=2.93M
y=2, x~=2.88M

## Current Behavior

y=0, 2978464
y=1, 2977288, diff = 1176
y=2, 2976176, diff = 1112

## Steps to Reproduce (for bugs)

1. Deploy contract
2. Call depth(0) with 3M gas, get value of x
3. Call depth(1), get value of x
4. Call depth(2), get value of x

## Context

I was testing this contract to try to understand (and protect against) stack depth attacks.

**Comment by benjaminion** [comment]
Can confirm.  Testrpc version info: `EthereumJS TestRPC v4.0.1 (ganache-core: 1.0.1)`

**Comment by benjamincburns** [comment]
This is an EVM bug. I've raised ethereumjs/ethereumjs-vm#255 to address it.

**Comment by benjamincburns** [comment]
And thanks for reporting, @carver!

**Comment by davidmurdoch** [comment]
Branch https://github.com/trufflesuite/ganache-core/commits/all-but-one-64th created for this issue,  including failing gas-estimation tests.

Still need to add tests to explicitly test the "All but one 64th" rule.

Because we don't properly estimate gas from the "All but one 64th" rule this one is blocked by https://github.com/trufflesuite/ganache-core/issues/147.

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!
