### ISSUE TITLE
With `-b 1` set on testrpc, truffle tests don't get js exceptions on `throw` in solidity

### ISSUE THREAD

**Issue by popra** [ConsenSys-archive/ganache-cli-archive#376]
## Expected Behavior
Regardless of `-b`, truffle should get exceptions when `throw` is encountered in solidity.

## Current Behavior
With `-b 1` set on testrpc, truffle doesn't get js exceptions on `throw` in solidity.
If `-b` is skipped, things work as expected.

## Steps to Reproduce (for bugs)

1. run `testrpc` with `-b 1`
2. from a truffle javascript test, run a transaction on the solidity contract function that `throws`
3. in the test, you should get an exception on the transaction. You don't

## Your Environment

* EthereumJS TestRPC v4.1.1 (ganache-core: 1.1.2) (happens with older versions too)
* Truffle v3.4.9 (core: 3.4.8) (happens with older versions too)
Solidity v0.4.15 (solc-js)
* node v8.4.0 (happens with 7 too)
* windows 10 (happens on mac too)

**Comment by tcoulter** [comment]
This is correct behavior. 

The `-b` option processes blocks as a normal blockchain. Like `geth` and `parity`, when `-b` is used, transactions aren't processed when the transaction is requested; instead, they're processed later, when the next block is processed. Since using `-b` specifies that you want transactions to be processed in blocks on an interval outside of the initial transaction request, you won't be able to receive runtime errors. 

Don't use `-b` if you'd like to receive runtime errors from the TestRPC.
