### ISSUE TITLE
Please fix your tests/npm install, so that someone can contribute.

### ISSUE THREAD

**Issue by kirtixs** [ConsenSys-archive/ganache-cli-archive#396]
Hi,

please fix your tests, they are failing for months on master.
I honestly want to submit some patches for open issues but this currently not possible since npm install wont work at all.

Can you please fix the npm install issues and make sure that the tests are running.
I just spend 3 hours trying to figure out what exactly is going wrong, but given that the last successful run on travis was ages ago, this is quite hard.

The best,
Simon

**Comment by holgerd77** [comment]
@redshark1802 The core development of this library has moved to https://github.com/trufflesuite/ganache-core (see [this note](https://github.com/ethereumjs/testrpc#developing)) and this repo is just for build/distribution, are you sure you want to contribute here (so something build-related)?

@tcoulter Will the travis build on this repo be re-activated at some time? Or is this just a left-over from the repository move and can be deactivated? The failing builds are also always irritating me when scanning over the ``ethereumjs`` travis build page.

**Comment by benjamincburns** [comment]
I just started two days ago, but I'm going to be maintaining TestRPC from here on out. The build will definitely be fixed up soon, but I have a few items on my plate and I'm traveling, so it may be a couple weeks yet until it's happy. Sorry for the inconvenience.

**Comment by holgerd77** [comment]
@benjamincburns Thanks for the quick answer, good to hear! :-)

I was just wondering: there is just neither ``tests`` file nor folder in this repo? Do you want to write this from scratch? Or there something lying somewhere around in the attic? :-)

**Comment by benjamincburns** [comment]
Not long before this issue was created we moved the bulk of logic into the ganache-core project, and moved our tests there as well. At around this time our build was red because travis was trying to run tests which didn't exist. That is long-since fixed.

Further in the near future @davidmurdoch is working on a few things which will further invalidate this case. Specifically he is:

1. Making our test suite more portable so we can run it against other targets without modification.
2. Moving the webpack build into ganache-core so our tests run against the packed logic rather than the unpacked logic.
