### ISSUE TITLE
msg.send.transfer not working in TESTRPC but good with Javascript VM & Injected Web3

### ISSUE THREAD

**Issue by santhochi** [ConsenSys-archive/ganache-cli-archive#398]
I am working through Windows Remix Solidity. msg.send.transfer() is not working in TESTRPC and giving out of gas error. But the same works in JavaScript VM (or) Injected Web3 connection through Metamask. I checked the gas limit used for the function in Injected Web3 and was only 29303. My TESTRPC already has a Gas limit of 4712388. Anyways, I increased the Gas limit to 99999999 and it doesn't work either. 

**My code**

contract testContract   {

    uint public balance;

    function sendEthers() payable {}
    
    function getBalance() constant returns (uint) {
        balance = address(this).balance;
        return balance;
    }
    
    function getEthers()  payable {
        msg.sender.transfer(address(this).balance);
    }
}

**Expected code Behaviour**

I am trying to send some ethers to Contract's address using sendEthers() function.
Then, I am getting it back using getEthers(). 

In TESTRPC, I am able to send Ethers successfully and verify it using getBalance() function. But, the getEthers() function errors out with Out of gas but works good with JavaScript VM or InjectedWeb3

**Error:**

transact to browser/Untitled.sol:testContract.getEthers errored: VM Exeception while processing transaction: out of gas

**Environment Details**
OS : Windows 10
Use remix Solidity, a web based IDE for writing and deploying Smart Contracts
TESTRPC version : EthereumJS TestRPC v4.1.3 (ganache-core: 1.1.3)

**Comment by vikas1188** [comment]
The problem that I can see straightforward is that the  **testrpc** doesn't consider the gas for internal txn, which in your case is being calculated by **metamask** (injectedWeb3).

I ran the code provided by you on ropsten using metamask. (I publish the code there as well to minimize the confusion)
https://ropsten.etherscan.io/address/0xb83d6886e8b06364627580e75989a4b467f88be1#code

There are 3 transactions that I performed on this contract. This is the address of the contract.
https://ropsten.etherscan.io/address/0xb83d6886e8b06364627580e75989a4b467f88be1

TX1 : Contract deployed
https://ropsten.etherscan.io/tx/0x7ddee73a2151c46ac0c79fa8c8a24b400a024fa2acff63a8faaa7c918d4fea54

TX2: sendEther() called with 0.1 Ethers.
https://ropsten.etherscan.io/tx/0x1212d9e2d66e76e6e42d560814acfb27c80d7f5619b31568d5e8c438c94719d1

TX3: getEthers() called. and you can see that it sends back the 0.1 ethers to the address. also, notice the INTERNAL TRANSATION tab. 
https://ropsten.etherscan.io/tx/0x0174b889cc62a842e0139bddbe20de92ba0c9eb519ca87cac1e5e2b20b169e20

Now the Testrpc team has to decide, how they can enable such sort of gas calculation like metamask, so that the testrpc can also calculate the gas for these operations beforehand and get away with the OOG error. 

Edit1: they already mentioned that they are implementing only these function calls.
https://github.com/ethereumjs/testrpc#implemented-methods

Thanks.

**Comment by saracad** [comment]
I'm having the same problem, on remix javascript vm everything works fine, i have a contract that sends something to another, on testrpc this operation returns success but balances doesn't change but on jvm they does

**Comment by benjamincburns** [comment]
> Now the Testrpc team has to decide, how they can enable such sort of gas calculation like metamask, so that the testrpc can also calculate the gas for these operations beforehand and get away with the OOG error.

Hi @vikas1188. I think you might be on the right track here, but you may be misunderstanding the role that ganache (formerly testrpc) is meant to play.

Ganache isn't a client in the same way that MetaMask is. Rather, it's meant to behave more like Infura, geth, or Parity. That is, when you fire off an `eth_sendTransaction` to Ganache or one of these other nodes implementations, they expect that you have called `eth_estimateGas` ahead of time, and set the `gas` parameter accordingly. If you don't specify the `gas` parameter, the default gas limit of 90000 is used. If this isn't enough gas, your transaction fails and `gas * gasPrice` ETH is lost. This default limit is documented in the [Ethereum JSON RPC wiki page here](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction).

Client libraries like `truffle-contract` or `web3` attempt to abstract some of this work away for you, but Infura, geth, Parity, and Ganache do not, nor is it a good idea for them to do so.

**Comment by benjamincburns** [comment]
Closing this one as it's quite old, and from what I can tell the issue stemmed from misunderstanding of gas limits moreso than an issue w/ ganache.

Please reopen if you feel this was a mistake.

**Comment by vikas1188** [comment]
Hi,
i got your point @benjamincburns . Thanks.
