### ISSUE TITLE
Stuck loading if port already in Use #bug

### ISSUE THREAD

**Issue by nikita-fuchs** [ConsenSys-archive/ganache-cli-archive#438]
Ganache is stuck in launching screen when the port is already in use.

## Expected Behavior
Show an error message.

## Current Behavior
Stuck at launching screen.

## Possible Solution
Show some warning.

## Steps to Reproduce (for bugs)

1. Start geth on :8545
2. Set Ganache to start on :8545

## Your Environment
* Version used: 1.0.1.
* Operating System and version: Ubuntu 16

**Comment by mikeseese** [comment]
Since this issue was created, we added the bug modal to display the EADDRINUSE error to the user.

Further,  we're making this more streamlined with https://github.com/trufflesuite/ganache/issues/665 and PR https://github.com/trufflesuite/ganache/pull/712

Thanks for reporting this however! Closing in favor of the above issue/PR

**Comment by pedroduartecosta** [comment]
For anyone who may run into this in the future. My problem was that I was **loading a truffle.js config** file and it was getting stuck on the loading screen.

Running `npm install` inside my project folder, where the truffle.js file is, **fixed** the problem.
