### ISSUE TITLE
Is this an error? if yes, how to solve it?

### ISSUE THREAD

**Issue by ongweijie** [ConsenSys-archive/ganache-cli-archive#461]
I have tried to install the ethereum-testrpc web3 on the node.js `8.9.4` but I keep getting this error. I don't know if it is a problem if I want to use this while learning how to code ethereum.
```
npm WARN deprecated ethereumjs-testrpc@6.0.3: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-11T09_41_42_045Z-debug.log
```

**Comment by benjamincburns** [comment]
That error is likely occurring because we have a dependency on something which is fetched from its git repository rather than the NPM package repository. NPM is complaining that you don't have Git installed on your system, so it can't fetch that package.

See the [dependencies section of the NPM `package.json` docs page](https://docs.npmjs.com/files/package.json#dependencies) for more info on this.

Finally, there's actually two things you need to fix here:

1. Install git, and/or make sure the directory where the `git` binary lives can be found in your `PATH` environment variable. Verify this by typing `git --version` from the command line. If you get version info, you should be in good shape.
2. **Please read and heed the top line of the output you pasted. The package `ethereumjs-testrpc` is no more. You'll want to `npm install -g ganache-cli` now.**

Hope this helps!

**Comment by ManUnit** [comment]
I solved this issue as below  :
$yarn add ethereumjs-testrpc
$yarn add fs-promise
$yarn add tar.gz 
$yarn add minimatch 
$yarn add web3 

< Anan@Bangkok >

**Comment by benjamincburns** [comment]
Hi @hs1gab,

When you did `yarn add ethereumjs-testrpc` you may have noticed a deprecation warning. We've renamed the module to `ganache-cli` and will no longer be publishing updates to `ethereumjs-testrpc`. I strongly encourage you to reference `ganache-cli` instead.

**Comment by ghost** [comment]
@ManUnit I followed what you suggested (except for ethereumjs-testrpc).  I still get the following error:

``` error /Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.4.1 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dipeshsukhani 1/.node-gyp/10.4.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/dipeshsukhani 1/.node-gyp/10.4.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/dipeshsukhani 1/.node-gyp/10.4.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/sha3/src/addon.o
clang: error: no such file or directory: '1/.node-gyp/10.4.1/include/node'
clang: error: no such file or directory: '1/.node-gyp/10.4.1/src'
clang: error: no such file or directory: '1/.node-gyp/10.4.1/deps/uv/include'
clang: error: no such file or directory: '1/.node-gyp/10.4.1/deps/v8/include'
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/sha3```

**Comment by ghost** [comment]
Here is the error through npm: 

```> scrypt@6.0.3 install /Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/scrypt/build'
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dipeshsukhani 1/Desktop/Truffle Testing/Courseto/node_modules/scrypt
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN courseto@1.0.0 No description
npm WARN courseto@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by mikeseese** [comment]
@DKSukhani These look like two separate issues. I don't think they quite relate to the original issue here, but here's my diagnosis anyway:

### The first one
I have a gut feeling this is an issue with your user name (`dipeshsukhani 1`) having a space in it (I'm not sure why that would be an issue, but I'm skeptical because of `no such file or directory: '1/.node-gyp/10.4.1/include/node'`

It looks like `node-gyp` is botching the commands: i.e. `'-Dnode_lib_file=/Users/dipeshsukhani 1/.node-gyp/10.4.1/<(target_arch)/node.lib',` does not have quotations around the path. Looks like the issue has been around since 2012: https://github.com/nodejs/node-gyp/issues/65. The issue is in `gyp` itself and still isn't patched. `node-gyp` is not willing to fix it. Looks like there might be some workarounds in that thread. I would consider removing the space from your user name (**please think about potential consequences, whatever those may be; it may screw stuff up, I'm not sure and you have been warned**)

### The second one
I have a gut feeling this is due to the first issue. Things aren't getting setup and folders aren't getting created maybe.
