### ISSUE TITLE
ganache-cli@beta not reporting failed transactions via truffle-contract

### ISSUE THREAD

**Issue by yarrumretep** [ConsenSys-archive/ganache-cli-archive#464]
## Expected Behavior
When invoking a contract function via truffle-contract that reverts, the truffle contract's promise should reject indicating that there was a VM execution error.  "VM Exception while processing transaction: revert"

## Current Behavior
When invoking a truffle-contract function that reverts (or otherwise errors) against ganache-cli@beta, the resultant Promise resolves rather than rejecting.  NOTE: the behavior is proper with ganache-cli@6.0.3

## Possible Solution
Not sure what the underlying cause is, but I've created a sample project that demonstrates this.

## Steps to Reproduce (for bugs)
Requires truffle.
1. npm install -g ganache-cli@beta
2. git clone https://github.com/yarrumretep/ganache-no-revert
3. cd ganache-no-revert
4. truffle test
Note that if you npm install -g ganache-cli, the test will pass.

## Context
Noticed this because we needed to use the develop ganache-core so we moved our version up.

## Your Environment
* Version used: ganache-cli@beta
* Version of Truffle/Remix/Other tools used: truffle 4.0.4
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [X] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): OS X 10.13.2
* Link to your project or repro gist: https://github.com/yarrumretep/ganache-no-revert
* Commit hash to use with above link for reproduction: master branch
* I intend to submit a pull request to fix this issue: [ ]

**Comment by yarrumretep** [comment]
UPDATE: I cannot recreate this on my linux box (Mint 18).  But have recreated with truffle 4.0.5 and ganache-cli@beta on my OSX box.

**Comment by benjamincburns** [comment]
@yarrumretep Thanks for reporting this! This is actually more of a `truffle-contract` bug than a `ganache-cli` bug. That is because, per the [release notes](https://github.com/trufflesuite/ganache-cli/releases/tag/v7.0.0-beta.0), we switched `ganache-cli` to report transaction failures in the same way that other clients (geth/Parity/etc) report transaction failures. 

This means that if `truffle-contract` is failing to catch transaction failures with `ganache-cli`, then it will also fail to catch them with geth, Parity, and other clients.

This is a known problem however, and we'll be updating `truffle-contract` before we make a stable release of `ganache-cli` `v7.0.0` or Ganache `v1.1.0`.

**Comment by yarrumretep** [comment]
Hi @benjamincburns - for the record , is there a git issue on truffle-contract that tracks this, I'm happy to log there if desired.  Or, even better, is there a beta of truffle-contract that fixes this?  I'm also happy to dive in if noone else has the baton on this one.

We really can't exercise your beta without this being fixed as our tests depend on rejected promises from truffle-contract to catch problems.

**Comment by benjamincburns** [comment]
Hi @yarrumretep. Definitely. I think trufflesuite/truffle-contract#93 is what you're looking for.
