### ISSUE TITLE
ganache-cli issue testing with MyEtherWallet - hello world

### ISSUE THREAD

**Issue by cryptoKevinL** [ConsenSys-archive/ganache-cli-archive#467]
## Expected Behavior
Trying to run a full stack hello world ethereum contract on Mac OS, using ganache-cli and MyEtherWallet.com on local host.  Ganache GUI doesn't work at all.

## Current Behavior
When I deploy a contract it shows:
Error: sender doesn't have enough funds to send tx. The upfront cost is: 5970310000000000 and the sender's account only has: 0 at runCall (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:76506:10) at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:13430:24 at replenish (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:10562:17) at iterateeCallback (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:10547:17) at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:10522:16 at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:13435:13 at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:72718:16 at replenish (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:72665:25) at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:72674:9 at eachLimit (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:72598:36)

Is there an option to give ETH value to a test account via ganache-cli?  I see the default balance in 100 ETH in the GUI but that doesn't work for me.

**Comment by psychoplasma** [comment]
Did you check whether or not the ganache-cli still works without crashing in the meantime? Because in my case when I try to sign a contract, the ganache-cli crashes which makes the wallet that you added drop to 0 ETH balance. And if you try to deploy that contract without knowing that the ganache-cli crashed, MyEtherWallet gives that error. But the more importantly what is the reason for the crash (in ganache-cli) while signing a contract which is,

 AssertionError: The field to must have byte length of 20
    at FakeTransaction.setter [as to] (/usr/lib/node_modules/ganache-cli/build/cli.node.js:7369:9)
    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:7419:63
    at Array.forEach (native)
    at Object.exports.defineProperties (/usr/lib/node_modules/ganache-cli/build/cli.node.js:7418:14)
    at FakeTransaction.Transaction (/usr/lib/node_modules/ganache-cli/build/cli.node.js:88365:13)
    at FakeTransaction (/usr/lib/node_modules/ganache-cli/build/cli.node.js:20465:5)
    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:90587:14
    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:21982:5
    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:67500:5
    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:67866:14

**Comment by cryptoKevinL** [comment]
That is a good point - I have had that crash, which seems to happen when I enter the bytecode into Remix compiler without the initial "0x", and then attempt to sign the contract.  I simply restarted the cli and thought that was good enough.

This is why I was hoping to have a function to reload balances to test accounts.  What is the solution here after this crash?  Do I just need to start an entirely new wallet or something further?

I was successful in running a smart contract using ganache-cli, truffle compiler, all cli.

**Comment by psychoplasma** [comment]
I think, every time you start the ganache-cli, it creates different wallets and if MyEtherWallet tries to check wallet balance that you added, it returns 0 balance, even if you restart ganache-cli. I mean you need to add a new wallet each time when you start the ganache-cli with those available accounts on the console. 

But anyways, I think that the main problem is that "AssertionError: The field to must have byte length of 20" error, at least in my case it is.

**Comment by benjamincburns** [comment]
@psychoplasma the assertion error you mention is fixed in current `develop` branch. I don't think that's the cause of @myFairCatsSick's issue.

@myFairCatsSick the question you asked in your most recent comment is probably best asked on [gitter](https://gitter.im/ConsenSys/truffle). However I think @psychoplasma's most recent comment likely applies. Also bear in mind that you can launch `ganache-cli` with the `--mnemonic` flag to guarantee that it recreates the same accounts on restart. You may also want to have a look at the `--account` flag in the README or in the helptext (run `ganache-cli --help`)

Closing, as I believe this is not a bug. Please reopen if you feel I'm mistaken.
