### ISSUE TITLE
Events not fired via websockets when using web3.eth.sendSignedTransaction

### ISSUE THREAD

**Issue by tomasgcs** [ConsenSys-archive/ganache-cli-archive#473]
## Context
Currently I'm using `1.0.0-beta.18` 

Connected via
`new Web3.providers.WebsocketProvider('ws://localhost:8545')`

## Expected Behavior
When using `web3.eth.sendSignedTransaction` and using websocket connection events should fire as soon as the transaction is mined.

## Current Behavior
When I try to use using `web3.eth.sendSignedTransaction`, the transaction is mined successfully, but the events emmited by the contract do not get fired but if I refresh my application and reconnect to `ganache-cli` events are received as expected.

But if I use `myContract.methods.myMethod().send` everything works fine, events get fired when the block is mined, without reconnecting to the node. 

result when using `web3.eth.sendSignedTransaction`

```javascript
{  
   "hash":"0xa78dfa11c19ba8e40476a16016f2d84894364cb289996c0a76dffbd1a4b70d64",
   "nonce":32,
   "blockHash":"0x677be9f216ee49e1334bb8e738c53ef60044cecbc7a73cb5e8409438e69d695d",
   "blockNumber":906,
   "transactionIndex":0,
   "from":"0x63C728caA8C9bbb1bb08dcbFE0132d6eDf03cbB6",
   "to":"0xc6F361795efF1b64dB552790b633158bc01e8d08",
   "value":"0",
   "gas":2000000,
   "gasPrice":"20000000000",
   "input":"0xb5b4f659000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000087361646661736466000000000000000000000000000000000000000000000000"
}
```

## Steps to Reproduce
Function call
```javascript
web3.eth.sendSignedTransaction('0x' + signedTransaction, function (err, hash) {
    if (err) {
        return callback(err);
    } else {
        return callback(null, hash);
    }
})
```

Result
```javascript
{  
   "hash":"0xa78dfa11c19ba8e40476a16016f2d84894364cb289996c0a76dffbd1a4b70d64",
   "nonce":32,
   "blockHash":"0x677be9f216ee49e1334bb8e738c53ef60044cecbc7a73cb5e8409438e69d695d",
   "blockNumber":906,
   "transactionIndex":0,
   "from":"0x63C728caA8C9bbb1bb08dcbFE0132d6eDf03cbB6",
   "to":"0xc6F361795efF1b64dB552790b633158bc01e8d08",
   "value":"0",
   "gas":2000000,
   "gasPrice":"20000000000",
   "input":"0xb5b4f659000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000087361646661736466000000000000000000000000000000000000000000000000"
}
```
Ganache Logs
```javascript
ganache         | eth_sendRawTransaction
ganache         | eth_getTransactionReceipt
ganache         | eth_subscribe
ganache         |
ganache         |   Transaction: 0xa78dfa11c19ba8e40476a16016f2d84894364cb289996c0a76dffbd1a4b70d64
ganache         |   Gas usage: 1226406
ganache         |   Block Number: 906
ganache         |   Block Time: Thu Feb 01 2018 02:01:51 GMT+0000 (UTC)
ganache         |
ganache         | eth_getTransactionReceipt
ganache         | eth_unsubscribe

```

Event listening
```javascript
contract.events[eventName]({
    fromBlock: 0
}).on('data', function (event) {
    <--NOT CALLED-->
}).on('changed', function (event) {
    <--NOT CALLED-->
}).on('error', function (err) {
    console.log(err);
});
```

**Comment by JamesLefrere** [comment]
I'm also experiencing this issue, though I can't see any reference to `sendSignedTransaction`; I'm finding this with `sendRawTransaction`, which is invoked with the library I'm using (https://github.com/ethers-io/ethers.js/).

I have been able to get this to work with an older version of Ganache (version 1.0.1 of the UI, not sure which version of ganache-core it's using), so I might have to do a bisect to find out the cause.

**Comment by benjamincburns** [comment]
> Currently I'm using 1.0.0-beta.18

@tomasgcs I think you might have a typo here? We haven't published a ganache, ganache-core, or ganache-cli release under that version. Perhaps that's your web3.js version?

FWIW, I ran into similar issues when updating our test suite to use web3.js 1.0. If you are using beta.18, I'd strongly advise updating to the latest web3.js 1.0 release, which is `1.0.0-beta.30` at time of writing.

Edit, sorry hit enter too soon.

Otherwise if you still experience the issue with latest web3.js, I'd advise troubleshooting by removing web3 from the equation altogether. You can send requests to ganache via the WebSocket provider simply by calling `provider.send(request, callback)` where `request` is a properly-formed JSON RPC 2.0 request, and `callback` is your typical `function(error, result)` style of callback.

Also bear in mind that when doing it this way if you set up a new subscription using `eth_subscribe`, you'll need to set up an event handler on the provider for the `data` event in order to receive subscription results. Simply doing `provider.on('data', (err, notification) => { console.log(JSON.stringify(notification, null, 2)) })` should be good enough to dump subscription notifications to the console.

If you manage to do this and you get the subscription results that you're after, it means that you're experiencing a bug in web3.js. If you don't get the subscription results that you want, you're either not setting the subscription filters up correctly, or you're experiencing a bug in ganache-core.

HTH

**Comment by mikeseese** [comment]
Closing due to age/inactivity.

Please open a new issue if you're still having problems. Thanks!
