### ISSUE TITLE
Is there a way to stop the automatic mining?

### ISSUE THREAD

**Issue by raindecastro** [ConsenSys-archive/ganache-cli-archive#477]
Hey everyone, sorry i'm just a beginner in this. I'm trying to do the mining manually rather than it automatically happening. Can anyone give me some help?

**Comment by benjamincburns** [comment]
Hi @raindecastro - the best place for beginners to ask questions is in the [Truffle Gitter](https://gitter.im/ConsenSys/truffle).

In the mean time, you're likely looking for `evm_start` and `evm_stop`. See the `README.md`.

Since you're asking, a common mistake beginners make is to use interval mining (that is, they specify a block time via the `-b` flag when they run `ganache-cli`). Unless your test cases require interval mining, I strongly recommend using instamining. To do this, just drop the block time flag from the command line, and your transactions will mine instantly.

**Comment by raindecastro** [comment]
Got it! thank you! it's working now, sorry about that! Thanks for giving me the link to Truffle Gitter will check that out for sure!
