### ISSUE TITLE
Support additional parameters for debug_traceTransaction

### ISSUE THREAD

**Issue by LogvinovLeon** [ConsenSys-archive/ganache-cli-archive#489]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ ]

## Expected Behavior

Currently in `ganache-cli` `debug_traceTransaction` doesn't respect any additonal configuration.
In Geth you can specify a [bunch of configs](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction)

I think `disableStorage`, `disableStack`, `disableMemory` are quite easy to implement and it will drastically increase the performance of the apps that don't actually need them.

## Current Behavior

It just ignores the additional params.

## Possible Solution

Filter the trace output before emiting it to the client or even don't generate it in the first place.

## Steps to Reproduce (for bugs)

1. Run ganache-cli/testrpc
2. Submit a contract transaction
3. Get it's trace by calling `debug_traceTransaction` and specifying `disableStack: true`
4. Stack variables are still there blowing up the size of the trace

## Context

I'm building a code coverage tool (and a gas usage profiler in future) based on traces and source maps. After each transaction I request the trace. If my transaction first pushed `n` elements to the stack and then executed `m` assembly instructions - the size of the trace will be proportional to `n*m` which is HUGE in real life scenarios. This makes tests much slower.

## Your Environment
* Version used: latest
* Version of Truffle/Remix/Other tools used: latest
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux): OSX
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]  (maybe)

**Comment by cgewecke** [comment]
@LogvinovLeon Hi. I work over at Truffle and contribute to `solidity-coverage` where we've also been talking [here](https://github.com/sc-forks/solidity-coverage/issues/150) and [here](https://github.com/sc-forks/solidity-coverage/issues/111) about re-writing the project to use an in-memory trace for a while, since its current instrumentation strategy is brittle and slow. Also think a gas-profiler is a great idea and because it involves the same underlying set of tasks as coverage would be a nice dividend of that work. Very excited to see that you are working on these ideas!

What do you think about the possibility of developing a tracing endpoint at Ganache that is an open-ended web-socket subscription for the relevant data, including vm steps taken during `.calls`? Have talked to @benjamincburns about this and he is open to supporting whatever tracing abilities the tools community wants or need. I hope to open a PR for this here in the next couple weeks and will include the parameters you've suggested. If you have any other ideas (or interest in writing code) for similar functionality there's an interested audience here :) and the sky's the limit.

Additionally - if you are working on coverage in your own org I would be happy to help. Conversely if you see any benefit to pursuing these projects at `solidity-coverage` I will gladly add you to the org there. 

Feel free to reach out to me or @benjamincburns about any of this! Thanks for this issue.

**Comment by cgewecke** [comment]
For further reference - some of the [coverage](https://github.com/0xProject/0x.js/pull/426) code referenced in the opening comment.
