### ISSUE TITLE
Running with noVMErrorsOnRPCResponse option does not return transaction on contract error

### ISSUE THREAD

**Issue by elenadimitrova** [ConsenSys-archive/ganache-cli-archive#493]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5aaa29ccf3f6d24c6878adc8

## Expected Behaviour
When running with `--noVMErrorsOnRPCResponse` option to return a valid transaction when a contract code errors. We should then be able to check if the transaction failed via its `status` property.

## Current Behaviour
Although the transaction executes, it is not returned back but an error:
```
Error: Transaction: 0x27bc3a834cc3219a2f016ba6e403cceb1f832802583b93c4d2b14cc2df9c8fc4 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
```
I expect to get back the transaction itself where I can check its status, just like parity and geth.

## Your Environment
* Version used: `ganache-cli@6.1.0`
* Version of Truffle/Remix/Other tools used: `truffle@4.1.3`

**Comment by cgewecke** [comment]
@elenadimitrova Truffle is responsible for this - it throws an error on status 0 because (after some debate) it was decided that doing otherwise would make it possible for tests to fail silently. The transaction receipt is being [appended to the error object](https://github.com/trufflesuite/truffle-contract/blob/develop/statuserror.js#L29-L31) as a key, ex: `err.receipt`.

**Comment by elenadimitrova** [comment]
Thanks for the explanation @cgewecke 
It's not what I expected but we can handle it.
