### ISSUE TITLE
Not able to Install ganache cli on windows 7

### ISSUE THREAD

**Issue by gargvivek86** [ConsenSys-archive/ganache-cli-archive#528]
I am trying to install ganache -cli on window 7, installation worked fine but when I am trying to run ganache cli command then it is showing that command not found.

**Steps to Reproduce**

1. Run below command

npm install -g ganache-cli

2. Run below command 

ganache-cli

**Logs for Step1**

C:\Windows\system32>npm install -g ganache-cli
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
C:\Users\vgarg1\AppData\Roaming\npm;npm\npm\ganache-cli -> C:\Users\vgarg1\AppData\Roaming\npm;npm\npm\node_modules\ganache-cli\build\cli.node.js
npm WARN webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

+ ganache-cli@6.1.0
updated 1 package in 43.544s

**Logs for Steps 2**

C:\Windows\system32>ganache-cli
'ganache-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mikeseese** [comment]
Hello!

Have you been able to use other globally installed npm modules? It's possible your windows PATH environment variable isn't setup to include the directory where global modules are installed. https://stackoverflow.com/questions/23400030/windows-7-add-path shows you how to add directories to the PATH environment variable.

I'll have to look up tomorrow on how to find the appropriate directory to add. This problem sounds like a Windows OS/NPM config issue rather than a Ganache install issue (looking at the logs you provided)

I'll try to help you further tomorrow

**Comment by gargvivek86** [comment]
Thanks Mike for your response. Below is the Path variable and I see get and npm there.

C:\Program Files\Geth;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\vgarg1\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin

**Comment by mikeseese** [comment]
@gargvivek86 see if this Stack Overflow question helps you: https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

A side note, I really like using NVM (manages different versions of NPM, etc). You can find the Windows port of NVM here: https://github.com/coreybutler/nvm-windows

**Comment by benjamincburns** [comment]
I'm going to close this as it's more of a node support request than an actual bug, and it seems like @seesemichaelj addressed the problem.
