### ISSUE TITLE
Access the reason string by using the flag --noVMErrorsOnRPCResponse. doesn't work

### ISSUE THREAD

**Issue by satyamakgec** [ConsenSys-archive/ganache-cli-archive#540]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]

## Expected Behavior
Accessing the ganache-cli with flag `--noVMErrorsOnRPCResponse` should provide a reason string if any revert occurs in accessing the solidity code.

## Current Behavior
I tried to work around with the ganache-cli using the same flag but it only gives me 
Error message, status, name, transaction and the receipt.

So I am not able to find a way to access the reason string. 

## Steps to Reproduce (for bugs)
A very simple way to reproduce the problem is listed below.

1. Create a contract which has a function that is using the require statement with the reason string.
2. Create the test case for the same function. which should fail at require statement.
3. Run the ganache-cli with `--noVMErrorsOnRPCResponse` flag
4. Run the test

## Your Environment
* Version used:
* Version of Truffle used: Truffle v4.1.11
* NodeJS Version:  9.11.1
* Operating System and version (include distro if Linux): OSX

**Comment by mikeseese** [comment]
Hello @satyamakgec, thanks for the write up! Unfortunately the revert reason string is not currently available in Ganache. It is currently waiting on https://github.com/trufflesuite/ganache-core/pull/106 (and even past that, a set of releases to be snapped). You can find the original issue to introduce this behavior here: https://github.com/trufflesuite/ganache-core/issues/116

**Comment by benjamincburns** [comment]
Hi @satyamakgec,

Unfortunately this behavior is as expected. By specifying `--noVMErrorsOnRPCResponse` you're telling ganache that you don't want RPC errors when transaction fail or revert. Since the reason string is sent as a member of the RPC `error` object, this closes the avenue for reporting the reason string. In this case your only option is to call `debug_traceTransaction` with the transaction hash returned in order to get the return value from the transaction (which will be your reason string).

cc @cgewecke, as he'll likely want to update `truffle-contract` to account for this.
