### ISSUE TITLE
Add CLI Flag for Websockets and Update NPM `beta` swimlanes

### ISSUE THREAD

**Issue by Revinand** [ConsenSys-archive/ganache-cli-archive#566]
Due to the master branch still does not have websocket support implemented, I'm forced to use beta version as described in #257. However automatic mining does not work in this version. My guess is that this is because of ganache-core version - 2.1.0-beta.7. Is it possible to update ganache-core dependency in the beta version or merge websocket support into the master?

**Comment by mikeseese** [comment]
Eek @Revinand! Thanks for pointing out there is CLI flag for websocket support, also thanks for pointing out our `beta` swimlanes(?) are grossly outdated. The issue you've pointed out (auto mining) is just due to this out of date releases

As part of this issue we'll do the following things:
- [ ] Add a CLI flag for wewbsockets in the mainstream tag/release stream/swimlane/thingy
- [ ] Update NPM `beta` tag to be in line with the `latest` tag or disable it when we're not using it. Poor management on our port

**Comment by mikeseese** [comment]
@Revinand while this issue is still prevalent, it looks like the [`ws` flag](https://github.com/trufflesuite/ganache-core#usage) to turn on the websocket server is turned on by default

You should be able to to use `ganache-cli@latest` to use websockets at this time. Let me know if you have any troubles or questions.

**Comment by Revinand** [comment]
@seesemichaelj thanks for the update! Will test it again shortly

**Comment by JackyKen** [comment]
it's great

**Comment by davidmurdoch** [comment]
Cleaned up npm beta tag.
