### ISSUE TITLE
evm_revert do not revert clock

### ISSUE THREAD

**Issue by adamskrodzki** [ConsenSys-archive/ganache-cli-archive#567]
## Expected Behavior

      `method: 'evm_revert'`
Should revert clock of blickchain to the time from snapshot it is reverting to
and ignore all increaseTimeTo invoked after snapshot has been made

## Current Behavior

if i call
`    web3.currentProvider.sendAsync({
      jsonrpc: '2.0',
      method: 'evm_snapshot',
      id: id,
    }, (err1,res) => {
      if (err1) return reject(err1);
      return resolve(res);
    });
  });`
then I call
increaseTimeTo

and then
`    web3.currentProvider.sendAsync({
      jsonrpc: '2.0',
      method: 'evm_revert',
      params:[snapId],
      id: id,
    }, (err1,res) => {
      if (err1) return reject(err1);
      return resolve(res);
    })`

Time is equal to the one set in latest increaseTimeTo

## Context

As It works now it makes impossible to write set of mutually independent tests all testing time dependent bechaviour. 

## Your Environment

truffle version
Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)

**Comment by benjamincburns** [comment]
Thanks for raising this, @adamskrodzki! We fixed this issue already in ganache-core, and it has been repaired for several releases. If you're still experiencing the problem when using `truffle develop` on the latest version of truffle, it's likely because truffle hasn't been updated to use latest ganache-cli in a while. I'll bring this to their attention.

Otherwise there's nothing left to be done in ganache-core, so I'm going to close this issue.
