### ISSUE TITLE
Error out of gas when use remix + Ganache CLI v6.1.8 (ganache-core: 2.2.1)

### ISSUE THREAD

**Issue by phuongvuong98** [ConsenSys-archive/ganache-cli-archive#585]
I want to send ethereum-coin to many address. When i use remix and Ganache CLI v6.1.8 (ganache-core: 2.2.1) (or testrpc), i have a problem out of gas. I ran with Javascript VM and my code is actived but i want to use my port to connect. I already try adjust gas limit and gas price but it didn't run correctly.

My problem: https://ibb.co/bR8vML

Why it have error? What is the way to solve my problem?

`    
            
    contract Send {
           function Send() public payable{
        
           }
        
           function () public payable{
           }
        
           function getBalance() constant returns (uint balance){
                balance = this.balance;
                return balance;
            }
        
            function transfer(address[] receiver, uint256 amount) payable public returns(bool){
                for(uint i = 0; i < receiver.length; i++){
                    receiver[i].send(amount);
                }
                return true;
            }   
        }
`

## Your Environment
* Version used: Ganache CLI v6.1.8 (ganache-core: 2.2.1)
* Version of Truffle/Remix/Other tools used: remix latest
* NodeJS Version: v8.10.0
* Operating System and version (include distro if Linux): linux 4.15.0-36-generic

**Comment by vishalburri** [comment]
Same problem can someone resolve this.

**Comment by davidmurdoch** [comment]
This bug should now be fixed in the latest beta of ganache-cli and ganache-core

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!
