### ISSUE TITLE
Method eth_signTransaction not supported.

### ISSUE THREAD

**Issue by e00dan** [ConsenSys-archive/ganache-cli-archive#601]
I'm using web3 1.0 method:

`const signedTx = await this.web3.eth.signTransaction(tx, options.from);`

However, I get error:

`(node:32116) UnhandledPromiseRejectionWarning: Error: Returned error: Method eth_signTransaction not supported.`

Ganache-cli has been started using:
`ganache-cli -m "shove afford modify census bridge good random error fault floor fringe oblige" -i 1002 -b 1`

Is there a reason ganache-cli doesn't support `eth_signTransaction`?

**Comment by davidmurdoch** [comment]
This is likely only because `eth_signTransaction` is _not_ currently part of the Ethereum JSON-RPC spec. Here is the EIP issue proposing to add it: https://github.com/ethereum/EIPs/issues/728

With that said, it looks like geth and parity already support it, as well as web3. MetaMask and ether.js have yet to add support.

As long as geth and parity agree on the implementation I don't see any harm in adding it to gananche in the future. I'll add this to our backlog. Thanks!

**Comment by Amxx** [comment]
> MetaMask and ether.js have yet to add support.

Metamask has been supporting it for ages

**Comment by davidmurdoch** [comment]
Closing in favor of https://github.com/trufflesuite/ganache-core/issues/408

**Comment by Kojo7** [comment]
@Amxx can you give an example how "web3.eth.signTransaction."  works in metamask, because I tried it and it did not work. Got the same error "Error: Returned error: Method eth_signTransaction not supported"
Ganache version:  2.1.2
web3 version : web3.js@1.0.0-beta.33 
Metamask version: 7.7.2

Thanks..!!!
