### ISSUE TITLE
Request: chainId Option

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys-archive/ganache-cli-archive#709]
## Expected Behavior

`chainId` should be an option

## Current Behavior

`eth_chainId` rpc call is implemented, but there's no way to set a custom `chainId`.

**Comment by davidmurdoch** [comment]
Thanks for opening this issue, @aakilfernandes. This is a feature that will ship in the next version. We are tracking it here: https://github.com/trufflesuite/ganache-core/issues/451 for a list of other breaking changes (this one is breaking because of a bug with how Ganache treats `chainId` internally).
