### ISSUE TITLE
test labels are mixed correct/failure behavior

### ISSUE THREAD

**Issue by kumavis** [ConsenSys-archive/ganache-cli-archive#98]
test labels are a mix of descriptions of correct behaviour and incorrect behaviour. this is confusing.

e.g.:

description of failure case `eth_estimateGas increased block count when it shouldn't have`
description of correct case `Transaction receipt shouldn't be null`

**Comment by tcoulter** [comment]
Is this an actual problem more than an artistic difference? The point of these messages is to tell the developer what happened in English rather than the more typical "2 does not equal 3", which doesn't provide semantic information. These messages are only shown when the test fails.

So, you'd interpret the first of your examples to be "Oh crap, there was a bug. It's because eth_estimateGas increased block count when it shouldn't have". And the second: "Oh crap, there was a bug. [The] transaction receipt shouldn't be null. [but is null]." 

After writing this out, I don't think that it's actually the issue you described. Both are descriptions of the failure that's shown to the developer.

**Comment by tcoulter** [comment]
Closed this. Reopen if you feel it's important.
